mainpage=restinfo.action.MainpageAction
login=restinfo.action.LoginAction
register=restinfo.action.RegAction
signUp=restinfo.action.SignUpAction
emailSend=restinfo.action.EmailSendAction
emailConfirm=restinfo.action.EmailConfirmAction
kakaoMap=restinfo.action.KaKaoMapV2
restArea=restinfo.action.RestAreaAction
logout=restinfo.action.LogoutAction
naverCallback=restinfo.action.NaverCallbackAction
kakaoCallback=restinfo.action.KakaoCallbackAction
mapinfo=restinfo.action.MapInfoAction
pjyrest=restinfo.action.PjyRestAreaAction
initSARA=restinfo.action.InitAreaAction
Cctv=restinfo.action.CctvAction
getVideoUrl=restinfo.action.VideoProxyAction
restAreaDetail=restinfo.action.pjyrestAreaDetail
getStatus=restinfo.action.getStatusAction
mypage=restinfo.action.MypageAction
deleteAccount=restinfo.action.deleteAccountAction
updateProfile=restinfo.action.updateProfileAction
bookmarkdelete=restinfo.action.bookmarkdeleteAction
getRestAreaDetails=restinfo.action.getRestAreaDetailsAction
getStores=restinfo.action.getStoresAction
Members=restinfo.action.MembersAction
Heartbookmark=restinfo.action.HeartBookmarkAction
updateFoodMenu=restinfo.action.UpdateFoodMenuAction
forgotPassword=restinfo.action.ForgotPasswordAction
#Board
notice=bbs.action.NoticeAction
faq=bbs.action.FaqAction
write=bbs.action.WriteAction
edit=bbs.action.EditAction
saveImg=bbs.action.SaveImgAction
view=bbs.action.ViewAction
del=bbs.action.DelAction
like=bbs.action.ReactionAction
hate=bbs.action.ReactionAction
searchAddress=restinfo.action.SearchAddress
download=bbs.action.DownloadAction

#단순 페이지 이동을 위한 property들
forgotPw=action.ForwardAction:/WEB-INF/views/forgotPw.jsp
resetPw=action.ForwardAction:/WEB-INF/views/resetPw.jsp
manage=action.ForwardAction:/WEB-INF/views/manage.jsp
Login=action.ForwardAction:/login.jsp
customerService=action.ForwardAction:/customerService.jsp
review=restinfo.action.ReviewAction
reviewLoadMore=restinfo.action.ReviewLoadMoreAction
